#!/bin/bash

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."


export NVM_DIR=$HOME/.nvm;
source $NVM_DIR/nvm.sh;

echo "==> Installing node version..."
nvm install


echo "==> Installing node modules..."
npm install

if [ -n "$1" ]; then
    echo "==> Seeding data..."
    npm run seed
else
    echo "==> Skipping seeding data..."
fi
