#!/bin/bash

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
if [ -s "$NVM_DIR/nvm.sh" ]; then
    source "$NVM_DIR/nvm.sh"
    echo "==> Installing node version..."
    nvm install
elif command -v nodenv 2>&1; then
    echo "==> Installing node version..."
    nodenv install --skip-existing
else
    echo "ERROR: nvm or nodenv not found"
    exit 1
fi


echo "==> Installing node modules..."
npm install

if [ "$1" = "--seed" ]; then
    echo "==> Seeding data..."
    npm run seed
else
    echo "==> Skipping seeding data..."
fi
