#!/bin/bash

# script/seed: Seeds the necessary data

set -e

cd "$(dirname "$0")/.."

export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
[ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh" && nvm use

echo "==> Seeding data..."
node --env-file=.env ./seed/repos.js && node --env-file=.env ./seed/lifetimes.js
