#!/bin/bash

# script/server: Launch the application

set -e

cd "$(dirname "$0")/.."

export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
[ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh" && nvm use

echo "==> Starting the server..."

node --env-file=.env index.js
